# configs/cherries_maturity.yaml
# Rutas *relativas* a este YAML  ➜  ../data  (= repo/data)
path: ../data            # <─ ¡sin rutas absolutas!
train: train/images
val:   val/images
test:  test/images

names:
  0: cherry_ripe
  1: cherry_halfripe
  2: cherry_unripe
